name: Vue website deployment

on:
  push:
    branches: [ 2024 ]
  pull_request:
    branches: [ 2024 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - name: install node modules
        run: bun install

      - name: build react app
        run: bun run build
        env:
          CI: ""

      - name: configure git user
        run: git config user.name github-actions

      - name: configure git email
        run:  git config user.email github-actions@github.com

      - name: deploy to github pages
        run: |
          git --work-tree build add --all
          git commit -m "deploy to github pages"
          git push origin HEAD:gh-pages --force