name: React app deployment

on:
  push:
    branches: [ 2023 ]
  pull_request:
    branches: [ 2023 ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: install node modules
      run: npm install

    - name: build react app
      run: npm run build
      env:
        CI: ""

    - name: configure git user
      run: git config user.name github-actions

    - name: configure git email
      run:  git config user.email github-actions@github.com

    - name: deploy to github pages
      run: |
        git --work-tree build add --all
        git commit -m "deploy to github pages"
        git push origin HEAD:gh-pages --force